local BB = _G.BigBankDepositPatternHighlighter

local MARKER_ALPHA = 0.055
local INITIAL_MARKER_COLOR = Color(0.075, 1, 0.45, 0)

local PATTERN_MARKER_COLORS = {
	[1] = Color(MARKER_ALPHA, 1, 0, 0),
	[2] = Color(MARKER_ALPHA, 1, 1, 0),
	[3] = Color(MARKER_ALPHA, 0, 1, 0),
	[4] = Color(MARKER_ALPHA, 0, 0, 1),
	[5] = Color(MARKER_ALPHA, 0, 1, 1),
	[6] = Color(MARKER_ALPHA, 1, 0, 1)
}

local config = {
	MARKER_DISPLAY_DISTANCE_SQ = 384400,
	OPENABLE_BOX_MATCH_DISTANCE_SQ = 90000,
	PATTERN_MARKER_COLORS = PATTERN_MARKER_COLORS,
	PROBE_GUIDE_INITIAL_MARKER_COLOR = INITIAL_MARKER_COLOR,
	SHOW_FULL_PATTERN = true,
	WORLD_MARKER_COLOR = INITIAL_MARKER_COLOR,
	WORLD_MARKER_FACE_OFFSET = 0.5,
	WORLD_MARKER_HEIGHT = 30,
	WORLD_MARKER_HEIGHT_INSET = 1,
	WORLD_MARKER_PIXEL_HEIGHT = 86,
	WORLD_MARKER_PIXEL_WIDTH = 112,
	WORLD_MARKER_LOCK_TO_CENTER_Y = 0.44,
	WORLD_MARKER_STROKE = 4,
	WORLD_MARKER_VERSION = 65,
	WORLD_MARKER_WIDTH = 42,
	WORLD_MARKER_WIDTH_INSET = 0.98
}

if BB then
	BB.shared = BB.shared or {}
	BB.shared.config_parts = BB.shared.config_parts or {}
	BB.shared.config_parts.marker = config
end

return config
